SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- SCHEMA ACXIONCHOCODATABASE
-- -----------------------------------------------------
DROP DATABASE IF EXISTS `ACXIONCHOCODATABASE`;
CREATE SCHEMA IF NOT EXISTS `ACXIONCHOCODATABASE` DEFAULT CHARACTER SET UTF8MB4 ;
USE `ACXIONCHOCODATABASE` ;

-- -----------------------------------------------------
-- TABLE `ACXIONCHOCODATABASE`.`DOCUMENTTYPE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ACXIONCHOCODATABASE`.`DOCUMENTTYPE` (
  `IDDOCTYPE` VARCHAR(3) NOT NULL,
  `DESCDOCTYPE` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`IDDOCTYPE`))
ENGINE = INNODB
DEFAULT CHARACTER SET = UTF8MB4;

-- -----------------------------------------------------
-- TABLE `ACXIONCHOCODATABASE`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ACXIONCHOCODATABASE`.`USER` (
  `IDUSER` VARCHAR(13) NOT NULL,
  `FK_IDDOCTYPE` VARCHAR(3) NOT NULL,
  `FIRSTNAME` VARCHAR(45) NOT NULL,
  `LASTNAME` VARCHAR(45) NOT NULL,
  `EMAIL` VARCHAR(50) NOT NULL,
  `PASSWORD` VARCHAR(200) NOT NULL,
  `PHONE` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`IDUSER`, `FK_IDDOCTYPE`),
  INDEX `FK_USER_DOCUMENTTYPE_IDX` (`FK_IDDOCTYPE` ASC) VISIBLE,
  CONSTRAINT `FK_USER_DOCUMENTTYPE`
    FOREIGN KEY (`FK_IDDOCTYPE`)
    REFERENCES `ACXIONCHOCODATABASE`.`DOCUMENTTYPE` (`IDDOCTYPE`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
)
ENGINE = INNODB
DEFAULT CHARACTER SET = UTF8MB4;

-- -----------------------------------------------------
-- TABLE `ACXIONCHOCODATABASE`.`ROLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ACXIONCHOCODATABASE`.`ROLE` (
  `IDROLE` VARCHAR(3) NOT NULL,
  `DESCROLE` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`IDROLE`))
ENGINE = INNODB
DEFAULT CHARACTER SET = UTF8MB4;

-- -----------------------------------------------------
-- TABLE `ACXIONCHOCODATABASE`.`USER_ROLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ACXIONCHOCODATABASE`.`USER_ROLE` (
  `IDUSER` VARCHAR(13) NOT NULL,
  `FK_IDDOCTYPE` VARCHAR(3) NOT NULL,
  `IDROLE` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`IDUSER`, `FK_IDDOCTYPE`, `IDROLE`),
  INDEX `FK_USER_ROLE_USER_IDX` (`IDUSER`, `FK_IDDOCTYPE` ASC) VISIBLE,
  INDEX `FK_USER_ROLE_ROLE_IDX` (`IDROLE` ASC) VISIBLE,
  CONSTRAINT `FK_USER_ROLE_USER`
    FOREIGN KEY (`IDUSER`, `FK_IDDOCTYPE`)
    REFERENCES `ACXIONCHOCODATABASE`.`USER` (`IDUSER`, `FK_IDDOCTYPE`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_USER_ROLE_ROLE`
    FOREIGN KEY (`IDROLE`)
    REFERENCES `ACXIONCHOCODATABASE`.`ROLE` (`IDROLE`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
)
ENGINE = INNODB
DEFAULT CHARACTER SET = UTF8MB4;

-- -----------------------------------------------------
-- TABLE `ACXIONCHOCODATABASE`.`COURSE`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `ACXIONCHOCODATABASE`.`COURSE` (
  `IDCOURSE` VARCHAR(6) NOT NULL,
  `COURSENAME` VARCHAR(60) NOT NULL,
  `COURSEDESCRIPTION` TEXT NOT NULL,
  `COURSEHOURS` INT NOT NULL,
  `PROFESSORNAME` VARCHAR(30) NOT NULL,
  `SEATCOUNT` INT NOT NULL,
  `ISAVAILABLE` TINYINT NOT NULL,
  `SCHEDULE` VARCHAR(50) NOT NULL,
  `MONITORNAME` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`IDCOURSE`))
ENGINE = INNODB
DEFAULT CHARACTER SET = UTF8MB4;

-- -----------------------------------------------------
-- TABLE `ACXIONCHOCODATABASE`.`COURSE_STUDENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ACXIONCHOCODATABASE`.`COURSE_STUDENT` (
  `IDCOURSE` VARCHAR(6) NOT NULL,
  `IDUSER` VARCHAR(13) NOT NULL,
  `FK_IDDOCTYPE` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`IDCOURSE`, `IDUSER`, `FK_IDDOCTYPE`),
  INDEX `FK_COURSE_STUDENT_COURSE_IDX` (`IDCOURSE` ASC) VISIBLE,
  INDEX `FK_COURSE_STUDENT_USER_IDX` (`IDUSER`, `FK_IDDOCTYPE` ASC) VISIBLE,
  CONSTRAINT `FK_COURSE_STUDENT_COURSE`
    FOREIGN KEY (`IDCOURSE`)
    REFERENCES `ACXIONCHOCODATABASE`.`COURSE` (`IDCOURSE`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_COURSE_STUDENT_USER`
    FOREIGN KEY (`IDUSER`, `FK_IDDOCTYPE`)
    REFERENCES `ACXIONCHOCODATABASE`.`USER` (`IDUSER`, `FK_IDDOCTYPE`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = INNODB
DEFAULT CHARACTER SET = UTF8MB4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
